/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanAvatar: typeof import('vant/es')['Avatar']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    ZjuLoginButton: typeof import('./src/components/zju-login-button.vue')['default']
  }
}

// For TSX support
declare global {
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const VanAvatar: typeof import('vant/es')['Avatar']
  const VanButton: typeof import('vant/es')['Button']
  const VanCard: typeof import('vant/es')['Card']
  const VanCell: typeof import('vant/es')['Cell']
  const VanCellGroup: typeof import('vant/es')['CellGroup']
  const VanField: typeof import('vant/es')['Field']
  const VanForm: typeof import('vant/es')['Form']
  const VanGrid: typeof import('vant/es')['Grid']
  const VanGridItem: typeof import('vant/es')['GridItem']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanImage: typeof import('vant/es')['Image']
  const VanList: typeof import('vant/es')['List']
  const VanNavBar: typeof import('vant/es')['NavBar']
  const VanSearch: typeof import('vant/es')['Search']
  const VanTab: typeof import('vant/es')['Tab']
  const VanTabbar: typeof import('vant/es')['Tabbar']
  const VanTabbarItem: typeof import('vant/es')['TabbarItem']
  const VanTabs: typeof import('vant/es')['Tabs']
  const VanTag: typeof import('vant/es')['Tag']
  const ZjuLoginButton: typeof import('./src/components/zju-login-button.vue')['default']
}